apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: redpanda
  namespace: redpanda-system
spec:
  interval: 1h
  url: https://charts.redpanda.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redpanda-operator
  namespace: redpanda-system
spec:
  interval: 15m
  chart:
    spec:
      chart: operator
      sourceRef:
        kind: HelmRepository
        name: redpanda
        namespace: redpanda-system
      version: ">=2.5.0"
  values:
    image:
      tag: v23.2.0
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

