apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redpanda-operator-vectorized
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redpanda-operator
rules:
- apiGroups:
  - redpanda.vectorized.io
  resources:
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/status
  verbs:
  - get
  - list
  - watch
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: redpanda-operator-vectorized
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/instance: redpanda-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redpanda-operator-vectorized
subjects:
- kind: ServiceAccount
  name: redpanda-operator
  namespace: redpanda-system

