apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: redpandas.cluster.redpanda.com
spec:
  group: cluster.redpanda.com
  names:
    kind: Redpanda
    listKind: RedpandaList
    plural: redpandas
    singular: redpanda
  scope: Namespaced
  versions:
  - name: v1alpha2
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}
  conversion:
    strategy: None

